### NumPy-Arrays

In [1]:
my_list = [1,2,3]

In [4]:
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]


In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,100) # evenly spaced 100 numbers between 0 to 5

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.23118768, 0.48001625, 0.07579582, 0.25816052, 0.67548606])

In [20]:
np.random.rand(5,5)

array([[0.14603518, 0.47536094, 0.74178905, 0.21575551, 0.72930518],
       [0.52265227, 0.71597552, 0.47273827, 0.99059247, 0.67984694],
       [0.83378794, 0.4360703 , 0.65519846, 0.53116621, 0.42115737],
       [0.52403518, 0.36802615, 0.76780292, 0.60283276, 0.19439212],
       [0.02421491, 0.102833  , 0.66980972, 0.26080257, 0.63144365]])

In [22]:
np.random.randn(2) # we will get normal distribution

array([0.99983609, 2.26069024])

In [25]:
np.random.randint(1,100,10) # random integer between 1 and 10

array([62, 34, 85, 46, 59, 14, 99, 57, 24, 85])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([21, 44, 14, 49, 18,  7, 42, 14, 34, 45])

In [30]:
# reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

49

In [37]:
ranarr.min()

7

In [40]:
ranarr

array([21, 44, 14, 49, 18,  7, 42, 14, 34, 45])

In [41]:
ranarr.argmax() # it will return the index of max value

3

In [42]:
ranarr.argmin()

5

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [48]:
arr.shape

(5, 5)

Data Type

In [49]:
arr.dtype

dtype('int32')

In [50]:
from numpy.random import randint

In [51]:
randint(2,10)

8