In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# broadcast

arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:] = 100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing

In [26]:
import numpy as np

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[2][1]

40

In [34]:
arr_2d[2,1]

40

In [35]:
arr_2d[1,2]

30

In [36]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [37]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [42]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

Conditional selection

In [43]:
arr = np.arange(1,11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
bool_arr = arr > 5

In [47]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr] # we will only get those values where it is True

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr < 3]

array([1, 2])

In [52]:
# create a 2d arr reshape it 5*10 . try to grab chunks. 13,14,23,24

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])